# Generated by Django 5.2.8 on 2025-11-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_userclass_usermanager_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
    ]
